### ISSUE TITLE
Issue about plotting one tile heatmap

### ISSUE THREAD

**Issue by ny-shao** [shenlab-sinai/geneoverlap-old#1]
When I plot only compare two conditions, so only one tile of the heatmap should be generated, like "x" is factor A and "y" is factor B, and only one tile of A comparing with B should be generated.
It triggered one exception of geneoverlap:

``` bash
KernSmooth 2.23 loaded
Copyright M. P. Wand 1997-2009
Error in 1:(nrow(plot.mat) - 1) : argument of length 0
Calls: drawHeatmap -> drawHeatmap
Execution halted
```

**Comment by lishen** [comment]
In this case, you should use a Venn diagram, not a heatmap. You can use GeneOverlap to obtain the statistics, though.

**Comment by lishen** [comment]
No source code changes needed.
